title: "Rafael Prévost: PI-OS"
email: rafael.prevost.15@gmail.com
favicon: assets/img/pi.png
github_pios: https://github.com/rafaelRiv/pi-os
github_aos: https://github.com/rafaelRiv/a-os
github_ros: https://github.com/rafaelRiv/r-os
description:
  "In this blog, we will write an operating system targeting the RISC-V architecture in Idris2 (mostly) and explore ideas from ATS and Rust.

  <h3>
  PI-OS: Making a RISC-V Operating System exploring depeding types using Idris2 
  </h3>"
baseurl: "/piblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: no-style-please
theme_config:
  show_description: true
plugins:
  - jekyll-feed

